version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    labels:
      - "Type: Maintenance"
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: "/"
    labels:
      - "Type: Maintenance"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/"
    labels:
      - "Type: Maintenance"
    schedule:
      interval: "weekly"
    groups:
      tauri-apps:
        patterns:
          - "@tauri-apps*"
          - tauri
          - tauri-build
      preact:
        patterns:
          - "@preact*"
          - "preact"
      9renpoto:
        patterns:
          - "@9renpoto*"
      storybook:
        patterns:
          - "@storybook*"
          - "storybook"
