version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    labels:
      - "Type: Maintenance"
    schedule:
      interval: "monthly"
    reviewers:
      - "9renpoto"
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: "/"
    labels:
      - "Type: Maintenance"
    schedule:
      interval: "monthly"
    reviewers:
      - "9renpoto"
    cooldown:
      default-days: 7
    groups:
      preact:
        patterns:
          - "@preact*"
          - "preact"
          - "preact-render-to-string"
      9renpoto:
        patterns:
          - "@9renpoto*"
      storybook:
        patterns:
          - "@storybook*"
          - "storybook"
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
          - "@codecov/astro-plugin"
      twind:
        patterns:
          - "@twind/*"
      testing:
        patterns:
          - "@testing-library/*"
          - "vitest"
          - "@vitest/*"
          - "happy-dom"
  - package-ecosystem: devcontainers
    directory: "/"
    labels:
      - "Type: Maintenance"
    schedule:
      interval: "monthly"
    reviewers:
      - "9renpoto"
    cooldown:
      default-days: 7
