version: 2
updates:
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '03:00'
    timezone: 'Asia/Tokyo'
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '03:00'
    timezone: 'Asia/Tokyo'
