# The name of the label to apply when an issue does not have all tasks checked
labelName: Status: In Progress

# The color of the label in hex format (without #)
labelColor: ccccc

# The text of the comment to add to the issue in addition to the label
commentText: >
	Please update the description correctly

# Whether or not to ensure all checkboxes are checked
checkCheckboxes: true

