- name: "good first issue"
  color: "5319e7"
  description: "Good for newcomers"
  aliases: []
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
  aliases: []
- name: "status: pending"
  color: c5def5
  description: "More info is needed before deciding what to do"
  aliases: []
- name: "status: pinned"
  color: 0052cc
  description: "Should not be labeled as stale"
  aliases: []
- name: "status: stale"
  color: fbca04
  description: "Inactive issues and PRs"
  aliases: []
- name: "status: wontfix"
  color: cfd3d7
  description: "This will not be worked on"
  aliases: []
- name: "type: bug"
  color: d73a4a
  description: "Verified problems that need to be worked on"
  aliases: []
- name: "type: chore"
  color: C5DEF5
  description: "Code changes that neither fix bugs nor add features (refactoring, dependency changes, ...)"
  aliases: []
- name: "type: docs"
  color: C5DEF5
  description: "Documentation changes"
  aliases: []
- name: "type: duplicate"
  color: cfd3d7
  description: "This issue or pull request already exists"
  aliases: []
- name: "type: feature"
  color: 0E8A16
  description: "New feature or feature request"
  aliases: []
- name: "type: fix"
  color: 1D76DB
  description: "Updates to existing functionalities"
  aliases: []
- name: "type: invalid"
  color: e4e669
  description: "This doesn't seem right"
  aliases: []
- name: "type: not a bug"
  color: 0e8a16
  description: "Reports that happen not be our fault"
  aliases: []
- name: "type: question"
  color: d876e3
  description: "Further information is requested"
  aliases: []
