version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
          message: This is work in progress. Do not merge yet.
      - do: description
        must_exclude:
          regex: \[ \]
          message: There are incomplete Todo task(s) unchecked.
      - do: label
        must_include:
          regex: ^Type
          message: must include types
