# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: ":boom: Type: Breaking Change"
      labels:
        - "Type: Breaking Change"
    - title: ":bug: Type: Bug"
      labels:
        - "Type: Bug"
        - "bug"
    - title: ":house: Refactoring"
      labels:
        - "Type: Refactoring"
    - title: ":memo: Documentation"
      labels:
        - "Type: Documentation"
        - "documentation"
    - title: ":rocket: Type: Feature"
      labels:
        - "Type: Feature"
        - "enhancement"
    - title: Other Changes
      labels:
        - "*"
