name: Deno

on:
  pull_request:
    paths:
      - "**.json"
      - "**.ts"
      - "**.tsx"
  push:
    branches:
      - main
    paths:
      - "**.json"
      - "**.ts"
      - "**.tsx"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check
