name: Node CI

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "**.json"
      - "**.ts"
      - "**.tsx"

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci

      - run: npm run build

      - run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server packages/ui/storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && npm test"

      - name: compressed-size-action
        uses: preactjs/compressed-size-action@2.8.0
        with:
          pattern: "./packages/ui/lib/**/*.{js,css,html,json}"
          exclude: "{**/*.map,**/node_modules/**}"

      - uses: codecov/codecov-action@v5

  quality:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .

  chromatic-deployment:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true # 👈 Required option to enable TurboSnap
          skip: "@(renovate/**|dependabot/**)"
