name: compressed-size

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: compressed-size-action
        uses: preactjs/compressed-size-action@2.1.0
        with:
          repo-token: "${{ secrets.github_token }}"
          pattern: "./apps/web/.next/**/*.{js,css,html,json}"
          exclude: "{**/*.map,**/node_modules/**}"
