name: Node CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*, latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - run: npm run build
      - run: npm run lint
      - run: npm test

      - run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && npm run test --workspace @app/ui -- --coverage"
      - run: sh -c "cd packages/ui && npx nyc report --reporter=lcov -t .nyc_output/ --report-dir coverage"

      - name: apps/web
        uses: coverallsapp/github-action@v2.2.1
        with:
          flag-name: web
          base-path: apps/web
          path-to-lcov: apps/web/coverage/lcov.info
          parallel: true

      - name: packages/ui
        uses: coverallsapp/github-action@v2.2.1
        with:
          flag-name: ui
          base-path: packages/ui
          path-to-lcov: packages/ui/coverage/lcov.info
          parallel: true
      - name: Codecov
        uses: codecov/codecov-action@v3.1.4

  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.github_token }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2.2.1
        with:
          parallel-finished: true
