name: Node CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*, latest]

    steps:
      - uses: actions/checkout@v3.5.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test

      - name: apps/web
        uses: coverallsapp/github-action@v2.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: web
          base-path: apps/web
          path-to-lcov: apps/web/coverage/lcov.info
          parallel: true

      - name: packages/ui
        uses: coverallsapp/github-action@v2.2.1
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: ui
          base-path: packages/ui
          path-to-lcov: packages/ui/coverage/lcov.info
          parallel: true
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2.2.1
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
