name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn build, and list
        run: |
          yarn install --frozen-lockfile
          yarn workspaces-to-typescript-project-references --check
          yarn build
          yarn lint
        env:
          CI: true
      - name: test
        run: |
          yarn test
          mkdir -p coverage
          yarn lcov-result-merger '{packages,apps}/*/coverage/lcov.info' 'coverage/lcov.info'
        env:
          CI: true

      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@0.2.1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: "packages/variables/coverage/lcov.info"

      - name: Codecov
        uses: codecov/codecov-action@v1.0.15

      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: variables
          base-path: packages/variables
          parallel: true
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
