name: Node and Rust
on:
  pull_request:
    paths:
        - 'apps/desktop/**'
        - 'Cargo.toml'
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v3
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - uses: tauri-apps/tauri-action@v0
        env:
          projectPath: apps/desktop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check
        if: matrix.platform == 'ubuntu-latest'
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: rustfmt
        if: matrix.platform == 'ubuntu-latest'
        run: cargo fmt --all --check
